<?php View::content(); ?>
<link href="<?php echo PUBLIC_PATH ?>css/plugins/dataTables.bootstrap.css"  rel="stylesheet" type="text/css">

<!-- Lista de usuarios -->
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="box box-success" >
      <div class="box-header">
        <h3 class="text-navy">Ver todos los usuarios</h3>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <div class="row">
          <div class="col-lg-12 col-md-12 small">
            <table class="table table-hover table-striped table-condensed" id="tabla_usuarios">
              <thead>
                <th>login</th>
                <th>Nombre</th>
                <th>activo</th>
                <th>Niveles</th>
                <th>Resetear clave</th>
                <th>Editar</th>
              </thead>
              <tbody>
                <?php foreach ($usuarios as $key): ?>
                  <tr>
                    <td><?php echo utf8_encode($key->login) ?></td>
                    <td><?php echo ($key->getNombre())   ?></td>
                    <td><?php echo $key->activo ?></td>
                    <td><?php echo $key->niveles_id ?></td>
                    <td><a href="<?php echo PUBLIC_PATH.'usuarios/resetear/'.$key->id?>"><i class="fa fa-eraser text-red"></i></a></td>
                    <td><a href="<?php echo PUBLIC_PATH.'usuarios/editar/'.$key->id?>"><i class="fa fa-pencil text-yellow"></i></a></td>
                  </tr>
                <?php endforeach ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--FIN: Lista de usuarios -->

<?php echo Form::open("usuarios/crear",'POST','class="form form-horizontal"'); ?>
<div class="row">
  <div class="col-lg-12">
    <div class="box box-primary">
      <div class="box-header"><h3>Registro de nuevo usuario</h3></div>
      <div class="box-body">
        <div class="col-lg-6 col-md-6">
          <div class="form-group">
            <label class="col-lg-3 col-md-3">Titulo</label>
            <div class="col-lg-5 col-md-5">
              <input type="text" name="usuarios[level]" id="usuarios_titulo" value="<?php echo @$_POST['usuarios']['titulo'] ?>" class="form-control mayuscula" placeholder="Titulo" required="">
              <div class="help-block with-errors"></div>
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 col-md-3">Nombre real</label>
            <div class="col-lg-8 col-md-8">
              <input type="text" name="usuarios[name]" value="<?php echo @$_POST['usuarios']['nombre'] ?>" class="form-control mayuscula" placeholder="Nombre real" required="">
            </div>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 col-md-3">A. paterno</label>
            <div class="col-lg-8 col-md-8">
              <input type="text" name="usuarios[apepat]" value="<?php echo @$_POST['usuarios']['paterno'] ?>" class="form-control mayuscula" placeholder="A. paterno">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 col-md-3">A. materno</label>
            <div class="col-lg-8 col-md-8">
              <input type="text" name="usuarios[apemat]" value="<?php echo @$_POST['usuarios']['materno'] ?>" class="form-control mayuscula" placeholder="A. materno">
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-6">
          <div class="form-group">
            <label class="col-lg-3 col-md-3">Nombre de usuario</label>
            <div class="col-lg-9 col-md-9">
              <input type="text" name="login" value="<?php echo @$_POST['usuarios']['login'] ?>" id="usuarios_login" class="form-control" placeholder="Usuario" required="" data-remote="<?php echo PUBLIC_PATH ?>usuarios/getExistente" delay="10">
            </div>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 col-md-3">Contraseña</label>
            <div class="col-lg-9 col-md-9">
              <input type="password" name="usuarios[pw]" id="clave" data-minlength="5" class="form-control" placeholder="Contraseña" required="" data-error="Minimo 5 caracteres">
            </div>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 col-md-3">Repite contr.</label>
            <div class="col-lg-9 col-md-9">
              <input type="password" name="usuarios[repite]" class="form-control"  placeholder="Repetir la contraseña"  data-match="#clave" data-match-error="Ups! No coinciden las contraseñas" required="">
            </div>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 col-md-3">Activo</label>
            <div class="col-lg-9 col-md-9">
              <select name="usuarios[activo]" class="form-control">
                <option value="S">Si</option>
                <option value="N" >No</option>
              </select>
            </div>
            <div class="help-block with-errors"></div>
          </div>
        </div>
      </div>
      <div class="box-footer">
        <div class="col-lg-3 col-md-3 pull-right">
          <button type="reset" class="btn btn-warning btn-flat" style="margin-right:10px;">Limpiar</button>
          <button type="submit" value="formulario" name="formulario" class="btn btn-success btn-flat">Registrar</button>
        </div> 
      </div>
    </div>     
  </div>
</div>
<?php echo Form::close(); ?>


<!-- Form close -->

<?php echo Tag::js('plugins/datatables/jquery.dataTables.min'); ?>
<?php echo Tag::js('plugins/datatables/dataTables.bootstrap.min'); ?>
