<?php View::content() ?>
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="box box-success" >
      <div class="box-header">
        <h3><?php echo $tequio->tipo.'  '.$tequio->fechatequio ?></h3>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <div class="row"> 
            <div class="col-md-12">  
              <fieldset>
                <legend>CIUDADANOS QUE ENTRAN EN LA CATEGORIA</legend> 
                <?php $ciudadanos= Load::model('ciudadanos')->getClasifica($tequio->fechatequio); ?>  
                <?php echo Form::open('tequios/formlista/'.$tequio->id) ?>                
                        <?php foreach ($ciudadanos as $key => $value): ?>
                            <?php $listar=load::model('tequiociudadano')->find_by_sql('select id from tequiociudadano where tequios_id = '.$tequio->id.' and ciudadanos_id = '.$value->id.' and asistio = "S"'); ?>
                                <?php if ($listar->id==null) : ?>
                                    <label class="container"><?php echo $value->getNombre().' -- / Casado '.$value->fechacasado.' / Predio '.$value->fechapredio.' / Ciudadania '.$value->fechaciudadano ?>
                                    <input class="listaciudadano" type="checkbox" name="listasistencia[]" value="<?php echo $value->id ?>"> 
                                    <span class="checkmark"></span>
                                    </label>
                                <?php endif ?>
                        <?php endforeach ?>
                        <input type="hidden" name="idtequio" value="<?php echo isset($tequio)?$tequio->id:'' ?>">
              </fieldset>
            </div>
            <div class="col-md-12 botones"> 
                <a href="<?php echo PUBLIC_PATH.'index/index/'?>" class="btn btn-danger btn-lg  pull-right">Cancelar</a>                
                <button class="btn btn-lg btn-success btn-flat pull-right boton">Guardar</button>
                <?php echo Form::close() ?>
            </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-12 col-md-12">
    <div class="box box-success" >
      <div class="box-header">
        <h3 class="text-navy">CIUDADANOS QUE ASISTIERON</h3>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <div class="row"> 
            <div class="col-md-12">  
              <fieldset>
                <legend>ASISTENCIA DE CIUDADANOS</legend> 
                    <?php $listar=load::model('tequiociudadano')->asistencias($tequio->id); ?>
                    <?php foreach ($listar as $key): ?>
                        <label class="container"><?php echo $key->nombre." /Capturo ".$key->capturista." /Con fecha ".$key->fecha ?>
                        </label>
                    <?php endforeach ?>
              </fieldset>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
    
    input {
        color:red;
    }
   .sinborde {
        border: 0;
    }
   .clase1{    
    font-size: 70%;
    font-family:'calibri';
    color:red;
    text-align:left;
   } 
   .clase2{    
    font-size: 70%;
    font-family: 'calibri';
    text-align:left;
   } 
    .clase3{    
    font-weight:bold;
    font-size: 70%;
    font-family: 'calibri';
    text-align:left;
   } 
    .clase4{        
    font-size: 100%;
    font-family: 'calibri';
    text-align:center;
    background-color:yellow;
   } 
   .clase5{
    font-weight:bold;
    font-size: 100%;
    font-family: 'calibri';
    text-align:left;
   }
  .complemento{
    background: #CDECF3;
 }   
 /*  div {
    border-top-style: solid;
    border-right-style: solid;
    border-bottom-style: solid;
    border-left-style: solid; 
   } */
.container {
    display: block;
    position: relative;
    padding-left: 35px;
    margin-bottom: 12px;
    cursor: pointer;
    font-size: 15px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}

/* Hide the browser's default checkbox */
.container input {
    position: absolute;
    opacity: 0;
    cursor: pointer;
}

/* Create a custom checkbox */
.checkmark {
    position: absolute;
    top: 0;
    left: 0;
    height: 25px;
    width: 25px;
    background-color: #eee;
}

/* On mouse-over, add a grey background color */
.container:hover input ~ .checkmark {
    background-color: #ccc;
}

/* When the checkbox is checked, add a blue background */
.container input:checked ~ .checkmark {
    background-color: #2196F3;
}

/* Create the checkmark/indicator (hidden when not checked) */
.checkmark:after {
    content: "";
    position: absolute;
    display: none;
}

/* Show the checkmark when checked */
.container input:checked ~ .checkmark:after {
    display: block;
}

/* Style the checkmark/indicator */
.container .checkmark:after {
    left: 9px;
    top: 5px;
    width: 5px;
    height: 10px;
    border: solid white;
    border-width: 0 3px 3px 0;
    -webkit-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    transform: rotate(45deg);
}

/*metodos de pruebas css */


</style>

