<?php echo view::content() ?>
<link href="<?php echo PUBLIC_PATH ?>css/plugins/dataTables.bootstrap.css"  rel="stylesheet" type="text/css">
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="box box-success" >
      <div class="box-header">
        <h3 class="text-navy">Todos los Tequios</h3>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <div class="row">
          <div class="col-lg-12 col-md-12 small">
            <table class="table table-hover table-striped table-condensed" id="tabla_tequios">
              <thead>
                <th>Tipo</th>
                <th>Organizador</th>
                <th>Fecha de tequio</th>
                <th>Activo</th>
                <th>Fecha creación</th>
                <th>Desactivar</th>
                <th>Activar</th>
                <th>Editar</th>
                <th>Pasar lista</th>
              </thead>
              <tbody>
              	<?php $tequios=Load::model('tequios')->find('fechacreacion IS NOT NULL and tipo IS NOT NULL and fechatequio IS NOT NULL') ?>
                <?php foreach ($tequios as $key): ?>
                <?php if ($key->activo=='S') : ?>                                                  
                  <tr>
                  	<td><?php echo $key->tipo ?></td> 
                  	<td><?php echo $key->organiza ?></td>
                  	<td><?php echo $key->fechatequio ?></td>
                  	<td><?php echo $key->activo ?></td>
                  	<td><?php echo $key->fechacreacion ?></td>
                    <td><a href="<?php echo PUBLIC_PATH.'tequios/desactivar/'.$key->id ?>"><i class="fa fa-pencil text-red"></i></a></td>
                    <td><a href="<?php echo PUBLIC_PATH.'tequios/activar/'.$key->id ?>"><i class="fa fa-pencil text-red"></i></a></td>                    
                    <td><a href="<?php echo PUBLIC_PATH.'tequios/formcreacion/'.$key->id?>"><i class="fa fa-pencil text-yellow"></i></a></td>
                    <td><a href="<?php echo PUBLIC_PATH.'tequios/formlista/'.$key->id?>"><i class="fa fa-pencil text-yellow"></i></a></td>
                  </tr>
                <?php else:?>                    
                <tr class="danger">
                  	<td><?php echo $key->tipo ?></td> 
                  	<td><?php echo $key->organiza ?></td>
                  	<td><?php echo $key->fechatequio ?></td>
                  	<td><?php echo $key->activo ?></td>
                  	<td><?php echo $key->fechacreacion ?></td>
                    <td><a href="<?php echo PUBLIC_PATH.'tequios/desactivar/'.$key->id ?>"><i class="fa fa-pencil text-red"></i></a></td>
                    <td><a href="<?php echo PUBLIC_PATH.'tequios/activar/'.$key->id ?>"><i class="fa fa-pencil text-red"></i></a></td>                    
                    <td><a href="<?php echo PUBLIC_PATH.'tequios/formcreacion/'.$key->id?>"><i class="fa fa-pencil text-yellow"></i></a></td>
                    <td><a href="<?php echo PUBLIC_PATH.'tequios/formlista/'.$key->id?>"><i class="fa fa-pencil text-yellow"></i></a></td>
                  </tr>                
                <?php endif?>
                <?php endforeach ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<?php echo Tag::js('formularios/formulariotequio') ?>
<?php echo Tag::js('plugins/datatables/jquery.dataTables.min'); ?>
<?php echo Tag::js('plugins/datatables/dataTables.bootstrap.min'); ?>