<?php echo View::content() ?>
  	<div class="error-page">
        <h2 class="headline text-yellow"> 404</h2>

        <div class="error-content">
          <h3><i class="fa fa-warning text-yellow"></i> Oops! Esta página no se encuentra disponible.</h3>

          <p>
            Esta página no esta disponible o ha ocurrido un error revise el proceso o intente entrar mas tarde.
          </p>
        </div>
        <!-- /.error-content -->
      </div>